# @package _global_
defaults:
  - /dataset/Nuscenes_cache_t
  # - /runner/default_t
  - _self_  # make sure override

# NOTE: we do not handle map explicitly, since on cache miss, our code can get
# the map from whole nuscenes map correctly. Therefore, we assume map is always
# available to every frame.

# use non-key frames
task_id: map_cache_gen_interp
log_root_prefix: outputs/cache_gen
dataset:
  dataset_cache_file_tag: 26x200x200_map_aux_full
  dataset_process_root: ./data/nuscenes_mmdet3d-12Hz/
  start_on_keyframe: false
  data:
    train:
      ann_file: ${...dataset_process_root}nuscenes_interp_12Hz_infos_train.pkl
      img_collate_param: ${img_collate_param}
    val:
      ann_file: ${...dataset_process_root}nuscenes_interp_12Hz_infos_val.pkl
      img_collate_param: ${img_collate_param}
    test:
      ann_file: ${...dataset_process_root}nuscenes_interp_12Hz_infos_val.pkl
      img_collate_param: ${img_collate_param}
model:
  video_length: 1
