# @package _global_
defaults:
  - /dataset/Nuscenes_map_cache_box_t_with_n2t

# this config only remove object items on map construction
# map size: (8, 200, 200)

dataset:
  dataset_cache_file_tag: 8x200x200_12Hz
  dataset_cache_dirname: nuscenes_map_aux_12Hz
  dataset_process_root: ./data/nuscenes_mmdet3d-12Hz/
  start_on_keyframe: false
  data:
    train:
      ann_file: ${...dataset_process_root}nuscenes_advanced_12Hz_infos_train_with_v.pkl
      fps: 12
    val:
      ann_file: ${...dataset_process_root}nuscenes_advanced_12Hz_infos_val_with_v.pkl
      fps: 12
    test:
      ann_file: ${...dataset_process_root}nuscenes_advanced_12Hz_infos_val_with_v.pkl
      fps: 12
