defaults:
  - _self_
  - dataset: Nuscenes_cache

task_id: "0.0.0"
log_root_prefix: outputs/
projname: MagicDriveDiT
hydra:
  run:
    dir: ${log_root_prefix}/${projname}_${now:%Y-%m-%d}_${now:%H-%M}_${task_id}
  output_subdir: hydra

img_collate_param:
  template: ${dataset.template}
  return_raw_data: True

seed: 42
